global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8001']
  
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8002']
  
  - job_name: 'shipping-service'
    static_configs:
      - targets: ['shipping-service:8003']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']